# Generated by Django 5.1.4 on 2026-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_personalevent_shared_with_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('trip', 'Business trip'), ('deadline', 'Deadline'), ('presentation', 'Presentation'), ('milestone', 'Milestone'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
