# Generated by Django 5.1.4 on 2026-06-08 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectmember_perm_defaults'),
        ('workspaces', '0007_team_teammember_team_teams_workspa_3ddef7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kind',
            field=models.CharField(choices=[('normal', 'Normal'), ('personal', 'Personal')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_personal_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'personal')), fields=('workspace', 'kind', 'owner'), name='unique_personal_project_per_user_ws'),
        ),
    ]
