# Generated by Django 5.1.4 on 2026-08-20 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0007_team_teammember_team_teams_workspa_3ddef7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_domain', models.CharField(max_length=100, unique=True)),
                ('client_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_sandbox', to=settings.AUTH_USER_MODEL)),
                ('workspaces', models.ManyToManyField(blank=True, related_name='demo_sandboxes', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'demo_sandboxes',
            },
        ),
    ]
