# Generated by Django 5.1.4 on 2026-05-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_issuecomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueattachment',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct upload'), ('from_comment', 'From comment editor')], default='direct', max_length=16),
        ),
    ]
