# Generated by Django 5.1.4 on 2026-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_issueattachment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='shared_with_team',
            field=models.BooleanField(default=True),
        ),
    ]
