# Generated by Django 5.1.4 on 2026-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_fix_category_sprint_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueattachment',
            name='size',
            field=models.PositiveIntegerField(default=0, help_text='File size (bytes)'),
        ),
        migrations.AlterField(
            model_name='issuetemplate',
            name='description_html',
            field=models.TextField(blank=True, default='', help_text='Default issue description (HTML)'),
        ),
        migrations.AlterField(
            model_name='issuetemplate',
            name='name',
            field=models.CharField(help_text='Template name', max_length=255),
        ),
        migrations.AlterField(
            model_name='issuetemplate',
            name='title_template',
            field=models.CharField(blank=True, default='', help_text='Default issue title', max_length=255),
        ),
    ]
