# Generated by Django 5.1.4 on 2026-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_ui_font_family_user_ui_font_mono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('feature', 'New feature'), ('improvement', 'Improvement'), ('bugfix', 'Bug fix'), ('notice', 'Notice')], default='notice', max_length=20),
        ),
    ]
