# Generated by Django 5.1.4 on 2026-08-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_team_teammember_team_teams_workspa_3ddef7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
