# Generated by Django 5.1.4 on 2026-09-15 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_teammember_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('project.trashed', 'Project Trashed'), ('project.restored', 'Project Restored'), ('project.purged', 'Project Purged'), ('project.archived', 'Project Archived'), ('project.unarchived', 'Project Unarchived'), ('project.lead_changed', 'Project Lead Changed'), ('project.member_added', 'Project Member Added'), ('project.member_removed', 'Project Member Removed'), ('project.member_role', 'Project Member Role'), ('space.visibility', 'Space Visibility'), ('space.archived', 'Space Archived'), ('space.unarchived', 'Space Unarchived'), ('space.deleted', 'Space Deleted'), ('space.member_added', 'Space Member Added'), ('space.member_removed', 'Space Member Removed'), ('space.member_role', 'Space Member Role'), ('space.personal_deleted', 'Personal Space Deleted'), ('member.role', 'Member Role'), ('member.removed', 'Member Removed'), ('invitation.sent', 'Invitation Sent'), ('invitation.revoked', 'Invitation Revoked'), ('join.approved', 'Join Approved'), ('join.rejected', 'Join Rejected'), ('team.deleted', 'Team Deleted'), ('api_token.created', 'Api Token Created'), ('api_token.revoked', 'Api Token Revoked'), ('webhook.created', 'Webhook Created'), ('webhook.updated', 'Webhook Updated'), ('webhook.deleted', 'Webhook Deleted')], max_length=40)),
                ('target_type', models.CharField(blank=True, default='', max_length=20)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='workspace_a_workspa_78531c_idx'), models.Index(fields=['workspace', 'action'], name='workspace_a_workspa_9653fe_idx')],
            },
        ),
    ]
