# Generated by Django 5.1.4 on 2026-08-19 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def copy_existing_members(apps, schema_editor):
    """기존 M2M(document_spaces_members)의 멤버를 전원 EDITOR 로 옮긴다.

    옛 테이블을 지우기 전에 실행돼야 한다(연산 순서 고정).
    EDITOR 로 넣는 이유: 지금까지 members 에 들어간 사람은 곧 편집 가능한 사람이었으므로,
    같은 등급으로 이관해야 권한이 넓어지지도 좁아지지도 않는다.
    """
    DocumentSpaceMember = apps.get_model("documents", "DocumentSpaceMember")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT documentspace_id, user_id FROM document_spaces_members")
        rows = cursor.fetchall()
    DocumentSpaceMember.objects.bulk_create(
        [
            DocumentSpaceMember(id=uuid.uuid4(), space_id=space_id, member_id=user_id, role=15)
            for space_id, user_id in rows
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_space_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSpaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(5, 'Viewer'), (15, 'Editor'), (20, 'Admin')], default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_space_roles', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_members', to='documents.documentspace')),
            ],
            options={
                'db_table': 'document_space_members',
            },
        ),
        migrations.AddIndex(
            model_name='documentspacemember',
            index=models.Index(fields=['space', 'role'], name='document_sp_space_i_3265e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentspacemember',
            unique_together={('space', 'member')},
        ),

        # 옛 M2M 테이블이 사라지기 전에 데이터부터 옮긴다
        migrations.RunPython(copy_existing_members, migrations.RunPython.noop),

        # Django 는 M2M 에 through= 를 붙이는 변경을 스키마 연산으로 처리하지 못한다.
        # 테이블 교체는 이미 위에서 끝났으므로, 여기서는 모델 state 만 새 정의로 맞춘다.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='documentspace', name='members'),
                migrations.AddField(
                    model_name='documentspace',
                    name='members',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='document_space_memberships',
                        through='documents.DocumentSpaceMember',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS document_spaces_members",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
