# Generated by Django 5.1.4 on 2026-08-19 02:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_space_member_roles'),
        ('workspaces', '0007_team_teammember_team_teams_workspa_3ddef7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_labels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_on', models.DateField()),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'document_views',
            },
        ),
        migrations.AddField(
            model_name='documentspace',
            name='home_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='documents.documentspace'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='scope',
            field=models.CharField(choices=[('built_in', 'Built-in'), ('user', 'User'), ('workspace', 'Workspace'), ('space', 'Space')], default='user', max_length=16),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['scope', 'space'], name='document_te_scope_7b22a5_idx'),
        ),
        migrations.AddField(
            model_name='documentlabel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentlabel',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_labels', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='document',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.documentlabel'),
        ),
        migrations.AddField(
            model_name='documentview',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentlabel',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='documentview',
            index=models.Index(fields=['document', '-viewed_on'], name='document_vi_documen_185834_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentview',
            unique_together={('document', 'user', 'viewed_on')},
        ),
    ]
