# Generated by Django 5.1.4 on 2026-09-14 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='links_hash',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='documents.document')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='documents.document')),
            ],
            options={
                'db_table': 'document_links',
                'indexes': [models.Index(fields=['target'], name='document_li_target__ab93fc_idx')],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
