# Generated by Django 5.1.4 on 2026-09-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_document_links_hash_documentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
