# Generated by Django 5.1.4 on 2026-09-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_document_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='db_columns',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
