# Generated by Django 5.1.4 on 2026-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_document_db_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled', max_length=500),
        ),
    ]
