# Generated by Django 5.1.4 on 2026-09-15 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0008_teammember_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(choices=[('read', 'Read'), ('write', 'Read & write')], default='read', max_length=8)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'api_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'user'], name='api_tokens_workspa_eff457_idx')],
            },
        ),
    ]
